"""auto add phone numbner

Revision ID: e124bb92d79b
Revises: 2adff2e19034
Create Date: 2026-01-31 08:42:30.354305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e124bb92d79b'
down_revision = '2adff2e19034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_unique_constraint("uq_cin", 'users', ['cin'])
    op.create_unique_constraint("uq_phone", 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_cin", 'users', type_='unique')
    op.drop_constraint("uq_phone", 'users', type_='unique')
    op.drop_column('users', 'phone')

    # ### end Alembic commands ###
